## Read Data from csv files

In [8]:
import pandas as pd 
import numpy as np

diagnosis = pd.read_csv('diagnosis.csv')
triage = pd.read_csv('triage_fixed.csv')
vitalsing = pd.read_csv('vitalsign_fixed.csv')
pyxis = pd.read_csv('pyxis.csv')
medrecon= pd.read_csv('medrecon.csv')
edstays = pd.read_csv('edstays.csv')

## list nulls for each table

In [12]:
#list nulls for each table
tables = [diagnosis, pyxis, medrecon, edstays, triage, vitalsing]

for df in tables:
    print(df.isnull().sum())
    print('-----------------------------')

subject_id     0
stay_id        0
seq_num        0
icd_code       0
icd_version    0
icd_title      0
dtype: int64
-----------------------------
subject_id        0
stay_id           0
charttime         0
med_rn            0
name              0
gsn_rn            0
gsn           35452
dtype: int64
-----------------------------
subject_id            0
stay_id               0
charttime             0
name                  0
gsn                   0
ndc                   0
etc_rn                0
etccode           11728
etcdescription    11728
dtype: int64
-----------------------------
subject_id                0
hadm_id              222071
stay_id                   0
intime                    0
outtime                   0
gender                    0
race                      0
arrival_transport         0
disposition               0
dtype: int64
-----------------------------
subject_id            0
stay_id               0
temperature       23948
heartrate         17130
resprate          20413
o2sat             20688
sbp               18291
dbp               19091
pain              12933
acuity             6987
chiefcomplaint       23
dtype: int64
-----------------------------
subject_id           0
stay_id              0
charttime            0
temperature     569351
heartrate        70446
resprate         89962
o2sat           136650
sbp              83992
dbp              82991
rhythm         1504960
pain            443266
dtype: int64
-----------------------------

## list duplicates for each table

In [13]:
# check for duplicates in each table
for df in tables:
    print(df.duplicated().sum())
    print('-----------------------------')

0
-----------------------------
0
-----------------------------
0
-----------------------------
0
-----------------------------
0
-----------------------------
0
-----------------------------

## List Data

In [14]:
triage.head()

,subject_id,stay_id,temperature,heartrate,resprate,o2sat,sbp,dbp,pain,acuity,chiefcomplaint
0,10000032,32952584,97.8,87.0,14.0,97.0,71.0,43.0,7,2.0,Hypotension
1,10000032,33258284,98.4,70.0,16.0,97.0,106.0,63.0,0,3.0,"Abd pain, Abdominal distention"
2,10000032,35968195,99.4,105.0,18.0,96.0,106.0,57.0,10,3.0,"n/v/d, Abd pain"
3,10000032,38112554,98.9,88.0,18.0,97.0,116.0,88.0,10,3.0,Abdominal distention
4,10000032,39399961,98.7,77.0,16.0,98.0,96.0,50.0,13,2.0,"Abdominal distention, Abd pain, LETHAGIC"

In [15]:
diagnosis.head()

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title
0,10000032,32952584,1,4589,9,HYPOTENSION NOS
1,10000032,32952584,2,07070,9,UNSPECIFIED VIRAL HEPATITIS C WITHOUT HEPATIC ...
2,10000032,32952584,3,V08,9,ASYMPTOMATIC HIV INFECTION
3,10000032,33258284,1,5728,9,"OTH SEQUELA, CHR LIV DIS"
4,10000032,33258284,2,78959,9,OTHER ASCITES

In [16]:
medrecon.head()

,subject_id,stay_id,charttime,name,gsn,ndc,etc_rn,etccode,etcdescription
0,10000032,32952584,2180-07-22 17:26:00,albuterol sulfate,28090,21695042308,1,5970.0,Asthma/COPD Therapy - Beta 2-Adrenergic Agents...
1,10000032,32952584,2180-07-22 17:26:00,calcium carbonate,1340,10135021101,1,733.0,Minerals and Electrolytes - Calcium Replacement
2,10000032,32952584,2180-07-22 17:26:00,cholecalciferol (vitamin D3),65241,37205024678,1,670.0,Vitamins - D Derivatives
3,10000032,32952584,2180-07-22 17:26:00,emtricitabine-tenofovir [Truvada],57883,35356007003,1,5849.0,Antiretroviral - Nucleoside and Nucleotide Ana...
4,10000032,32952584,2180-07-22 17:26:00,fluticasone [Flovent HFA],21251,49999061401,1,371.0,Asthma Therapy - Inhaled Corticosteroids (Gluc...

In [17]:
pyxis.head()

,subject_id,stay_id,charttime,med_rn,name,gsn_rn,gsn
0,10000032,32952584,2180-07-22 17:59:00,1,Albuterol Inhaler,1,5037.0
1,10000032,32952584,2180-07-22 17:59:00,1,Albuterol Inhaler,2,28090.0
2,10000032,35968195,2180-08-05 22:29:00,1,Morphine,1,4080.0
3,10000032,35968195,2180-08-05 22:55:00,2,Donnatol (Elixir),1,4773.0
4,10000032,35968195,2180-08-05 22:55:00,3,Aluminum-Magnesium Hydrox.-Simet,1,2701.0

In [18]:
vitalsing.head()

,subject_id,stay_id,charttime,temperature,heartrate,resprate,o2sat,sbp,dbp,rhythm,pain
0,10000032,32952584,2180-07-22 16:36:00,NaN,83.0,24.0,97.0,90.0,51.0,NaN,0
1,10000032,32952584,2180-07-22 16:43:00,NaN,85.0,22.0,98.0,76.0,39.0,NaN,0
2,10000032,32952584,2180-07-22 16:45:00,NaN,84.0,22.0,97.0,75.0,39.0,NaN,0
3,10000032,32952584,2180-07-22 17:56:00,NaN,84.0,20.0,99.0,86.0,51.0,NaN,NaN
4,10000032,32952584,2180-07-22 18:37:00,98.4,86.0,20.0,98.0,65.0,37.0,NaN,NaN

In [19]:
edstays.head()

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
0,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,F,WHITE,AMBULANCE,ADMITTED
1,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,F,WHITE,AMBULANCE,ADMITTED
2,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,F,WHITE,AMBULANCE,ADMITTED
3,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,F,WHITE,AMBULANCE,HOME
4,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,F,WHITE,AMBULANCE,ADMITTED

## List Unique Values for edstays table

In [29]:
edstays.head()

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
0,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,F,WHITE,AMBULANCE,ADMITTED
1,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,F,WHITE,AMBULANCE,ADMITTED
2,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,F,WHITE,AMBULANCE,ADMITTED
3,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,F,WHITE,AMBULANCE,HOME
4,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,F,WHITE,AMBULANCE,ADMITTED

In [23]:
#edstays race unique values
edstays.race.unique().tolist()

['WHITE',
 'ASIAN',
 'OTHER',
 'ASIAN - SOUTH EAST ASIAN',
 'UNKNOWN',
 'BLACK/AFRICAN AMERICAN',
 'ASIAN - CHINESE',
 'WHITE - RUSSIAN',
 'BLACK/CAPE VERDEAN',
 'PORTUGUESE',
 'MULTIPLE RACE/ETHNICITY',
 'UNABLE TO OBTAIN',
 'WHITE - OTHER EUROPEAN',
 'HISPANIC/LATINO - DOMINICAN',
 'HISPANIC/LATINO - SALVADORAN',
 'HISPANIC/LATINO - PUERTO RICAN',
 'WHITE - BRAZILIAN',
 'HISPANIC/LATINO - GUATEMALAN',
 'BLACK/CARIBBEAN ISLAND',
 'HISPANIC OR LATINO',
 'BLACK/AFRICAN',
 'AMERICAN INDIAN/ALASKA NATIVE',
 'ASIAN - KOREAN',
 'WHITE - EASTERN EUROPEAN',
 'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER',
 'HISPANIC/LATINO - MEXICAN',
 'PATIENT DECLINED TO ANSWER',
 'HISPANIC/LATINO - CUBAN',
 'HISPANIC/LATINO - COLUMBIAN',
 'ASIAN - ASIAN INDIAN',
 'SOUTH AMERICAN',
 'HISPANIC/LATINO - HONDURAN',
 'HISPANIC/LATINO - CENTRAL AMERICAN']

In [22]:
edstays.arrival_transport.unique().tolist()

['AMBULANCE', 'WALK IN', 'UNKNOWN', 'OTHER', 'HELICOPTER']

In [24]:
edstays.disposition.unique().tolist()

['ADMITTED',
 'HOME',
 'LEFT WITHOUT BEING SEEN',
 'TRANSFER',
 'ELOPED',
 'OTHER',
 'LEFT AGAINST MEDICAL ADVICE',
 'EXPIRED']

In [25]:
edstays.gender.unique().tolist()

['F', 'M']

## Explore Vitalsign

In [28]:
vitalsing.head()

,subject_id,stay_id,charttime,temperature,heartrate,resprate,o2sat,sbp,dbp,rhythm,pain
0,10000032,32952584,2180-07-22 16:36:00,NaN,83.0,24.0,97.0,90.0,51.0,NaN,0
1,10000032,32952584,2180-07-22 16:43:00,NaN,85.0,22.0,98.0,76.0,39.0,NaN,0
2,10000032,32952584,2180-07-22 16:45:00,NaN,84.0,22.0,97.0,75.0,39.0,NaN,0
3,10000032,32952584,2180-07-22 17:56:00,NaN,84.0,20.0,99.0,86.0,51.0,NaN,NaN
4,10000032,32952584,2180-07-22 18:37:00,98.4,86.0,20.0,98.0,65.0,37.0,NaN,NaN

In [27]:
vitalsing.pain.unique().tolist()

['0',
 nan,
 '5',
 'asleep',
 'unable',
 'uta',
 'u',
 '3',
 '0/10',
 '7',
 '8',
 '2',
 '1',
 '6',
 '4',
 'sleeping',
 '9:10',
 '1:10',
 'critical',
 '0.',
 '10',
 '9',
 'resting',
 '2/10',
 '3/10',
 'Asleep',
 'ua',
 'sleep',
 '7-8',
 'UTA',
 'Non-verbal',
 'agitated',
 'ETT',
 'ett',
 'sleepin',
 'left arm',
 'right arm',
 '2-3',
 'Denies',
 'see nsg note',
 '2/10 knee',
 'u/a',
 '3-4',
 'Critical',
 '1/10',
 '8/10',
 '4 at rest',
 'c',
 'sedated',
 'laying',
 'sitting',
 'standing',
 'unable ',
 '010',
 'does not scale',
 '"pain"',
 '-',
 'UA',
 '8.5',
 'refused',
 'refusing',
 'refuse',
 '2o',
 'sleep ',
 '0-3',
 'NAD',
 '6/10',
 'grimace with palpation',
 'denies',
 'laying down',
 'sitting ',
 'standing ',
 '5/10',
 '5-6',
 'denies ',
 'yes',
 '7/10',
 '6-7',
 'Sleeping',
 '5.5',
 'asleep ',
 '1-2',
 'intubated',
 'Unable',
 '0-1',
 'lying down',
 '3.5',
 '8.4',
 '2l',
 'o',
 '8-9',
 'ok',
 'S',
 '0-10',
 '"better"',
 '6-7/10',
 'uncooperative',
 'Pt left prior to VS/work note',
 'back 8/10',
 '4/10',
 'comfortable',
 '0.5',
 '7.5',
 'sleeping ',
 'pt unable to tell RN',
 'sedation',
 '04',
 '9/10',
 '3t',
 'Supine',
 'Sitting',
 'Standing',
 'unable to scale - pt c/o mid abd pain',
 'unable to scale',
 '10/10',
 '"pretty high"',
 'U',
 'pre-hosp',
 'intubateded',
 'y',
 'does not appear to',
 '+',
 '9-10',
 '"10"',
 'refused ',
 'Refused',
 '4-5',
 'uable',
 'amnulatory O2 saturation',
 'UNABLE',
 'Laying',
 'vent',
 'I',
 'RA',
 '?',
 'ett ',
 'crit',
 'UTA ',
 'uta ',
 'uanble',
 'uanble ',
 '0-6',
 '9.5',
 '"ok"',
 'pain',
 '" pain better"',
 '"none"',
 '00',
 'moaning',
 '"yes"',
 'Laying Down',
 '4.5',
 'STANDING',
 'sleepng ',
 '8-10',
 'moderate',
 'unknown',
 'alseep',
 ' 0',
 '"sore"',
 'sore',
 'T',
 '6.5',
 '0 at rest',
 'SLEEPING',
 'Pt Refused Vitals',
 'Pt refusing VS',
 'Uta',
 'ams',
 '"pressure"',
 'intubation',
 'reports "painful"',
 '6 - 8',
 'Y',
 'ASLEEP',
 'unsure',
 '2-3/10',
 'unclear',
 '0-2',
 '3:10',
 'ASleep',
 '0 ',
 '1.5',
 'ua156/90',
 'Ambulatory',
 'does not scale. ',
 'pt unable',
 '4-5/10',
 'lying',
 '"a lot"',
 '"terrible"',
 '"good"',
 '1-4',
 'pre hosp',
 '"so much"',
 '3 cramping',
 'ETCO2 37',
 'ETCO2 27',
 'ETCO2 36',
 '12',
 '"no"',
 'lethargic',
 '0P',
 '10 ',
 'unresponsive',
 'unrespopnsive',
 '3-9',
 ' 8',
 'ambulating',
 '0-4',
 'f',
 'intaubated',
 'intbated',
 'UTR',
 '1.5-2',
 'critical ',
 '"alot"',
 'Pt states he is unable to give me a number ',
 'pt states he is unable to rate pain',
 'Lying down',
 'Sitting upright',
 's',
 'UTA - OFF PROP FOR NEURO',
 'UTA - prop restarted for CT',
 'ETCO2 = 35',
 'UTA - ETCO2 = 32',
 'UTA - ETCO2 = 34',
 '10 comes in waves',
 'aslep',
 '0 cp',
 '7 with movement',
 '7-8/10',
 'AMBULATORY',
 '___',
 '4-10',
 'Bad',
 'SITTING',
 'Sleeping ',
 '"a little"',
 'movement',
 'not bad',
 '7 (HA)',
 '5 (HA)',
 'cant keephis eyes open',
 'sleepng',
 'ra',
 'sleeeping',
 'pressure',
 '"feels like shit"',
 'sitting up',
 '4./10',
 'UNABLE ',
 '01',
 'O',
 '"8"',
 'tight',
 'pt upset',
 '.',
 '10/10 abd',
 ' 10',
 '3-from migraine',
 'mild',
 'less than 1',
 'etCo2 59',
 'etCo2 42',
 'etCo2 37',
 'etco2 50',
 'etco2 31',
 'grimacing',
 'SLEEP',
 'uto',
 '"feels like I have to burp"',
 '4 under arm, 10 leg',
 '3-6',
 '4&9',
 'lido',
 'intubuated',
 'intubuated ',
 '3 tolerable lower abd since surgery',
 'unable to assess',
 'Tearful',
 'Intermittent pain',
 '"good" per granddaughter',
 '7/8',
 'too much',
 'better',
 'unable to rate',
 'unable  ',
 '10+',
 '9-10/10',
 'unqble',
 'unABLE',
 '0-8',
 '0-',
 'v',
 'tong',
 'PAIN ',
 '0:10',
 'pinching',
 'awake, unable to state',
 'MRI',
 'sitting down',
 'see trauma flow sheet',
 '8z',
 'unable to quantify',
 '"little"',
 'ssomulent',
 'somnulent',
 'unable to give #',
 'non-verbal ',
 '3-5',
 'Unknown',
 'Pain after ambulation to restroom',
 '.0',
 'unresp',
 '0 faces',
 '0 FACES',
 '"hurts"',
 '7/10 chest',
 '6/10 chest',
 'did not answer',
 'no',
 'intub',
 'LAYING DOWN',
 '"annoying"',
 'Unresponsive',
 'unable to describe',
 '"2000/10"',
 '"900/10"',
 'intubate',
 '7 (while ambulating)',
 '0/',
 '"some"',
 'tightness',
 '0/100',
 'intuabted',
 'unable to score - abd pain',
 '3-4/10',
 'aleeping',
 'R ARM',
 'L ARM',
 '\'ouch"',
 'ouch',
 'supine',
 'ETCO2 30',
 '1-10',
 'walking',
 '8/10 ',
 '.5',
 '"not bad"',
 '5-6/10',
 'cramps',
 '"some pain in arm and leg"',
 'asleeptrop ele',
 'unk',
 'ref',
 'vented',
 'not strong at all',
 'moans to painful stim.',
 'moans with painful stimuli',
 'unknwn',
 'uts',
 'refused to rate pain.',
 'utA',
 '0-9',
 'med',
 '6:10',
 '5-8',
 '3/10, facial',
 '0 symptoms',
 '0 symptom',
 'Left Arm ',
 'right arm ',
 '>10',
 '2/10 Numbers',
 '"A LITTLE"',
 'LAYING',
 'sleeoing',
 'Intub.',
 'intub.',
 'vented/no facial grimacing or writhing',
 '4 back pain',
 '3/4',
 '0-5',
 '4-6',
 'sleepoing',
 'dull ache/10',
 '0.2/10',
 'UTa',
 'sleepingh',
 '1-1 1/2',
 '1/2',
 '1/2-1',
 '3T',
 '"it hurts"',
 '"it hurts alot"',
 ' 7',
 'pain down to 5 from 8',
 'non verbal',
 '3-8/10',
 ' yes, unable',
 'yes, unable to rate',
 'Laying down',
 'sort of',
 'criot',
 'unable to quantify d/t language barrier',
 'p',
 'pt states its there but less than 10',
 'pt states shse isnt in severe pain',
 '"Bad"',
 '"mild"',
 'utr',
 'laying down, denies dizziness',
 'sitting, denies dizziness',
 'standing, denies dizziness',
 '3.375',
 '3.75',
 '3.25',
 '3.45',
 '8 (faces)',
 '5 (faces)',
 'headache',
 'ambulatory',
 '"itchy"',
 'FACES 3',
 'FACES 2',
 'ETT ',
 'Ett',
 '4.5-5',
 'appears comfortable',
 'utra',
 '0Af',
 '0,10',
 'prehosp',
 '0/11',
 'us',
 'unable. ',
 'unabl4',
 '1 ',
 'some',
 'little',
 'eyes closed, does not appear in distress',
 'does not verbalize',
 '4/10 HA',
 "snoozin'",
 'a lot',
 'Decined',
 'sleepinh',
 'pain is in back unable to rate',
 'non-verbal',
 '"I\'m OK"',
 '7:10',
 'on movement',
 'weakness',
 'throbbing',
 '1/7',
 'unable to say',
 '2-4/10',
 'alot',
 '8/9',
 '33/',
 'Sleep',
 'bad',
 '2 h/a',
 '4:10',
 'HA',
 'sleping',
 '5 at rest',
 '5at rest 10 w mvt',
 '5at rest / 10 w mvt',
 'sleepimg',
 '0/10 CP',
 '0/10 cp',
 '5-9/10',
 'sedated ',
 'improved',
 '07',
 'etco233',
 'h/a',
 '8  ',
 '05',
 '"heavy pressure" center of chest, unchanged from intial exam',
 'NAD, resting in stretcher with eyes closed',
 ' 6/10',
 'Etco2 20',
 'very bad',
 '0a',
 'unabel',
 '08',
 'laying ',
 'declined',
 'ache',
 '6/7',
 '3.5/10',
 '4 ',
 'pt refused BP.',
 'aches',
 '52',
 'MILD',
 '"okay"',
 '"still there"',
 'u/z',
 '6/10 ',
 'a little',
 ' asleep',
 'error',
 '4-8/10',
 'FLACC 0',
 'not answering',
 '5 "tolerable"',
 'Laying down ',
 'Sitting ',
 'lots',
 '8 or 9',
 '"much better"',
 'RUE',
 'R arm',
 'ttp',
 'unable to score',
 ' unable',
 '2:10',
 'it hurts',
 '++',
 'crying',
 '2.5',
 '2./10',
 '"I can\'t tell"',
 'unable to report',
 '11',
 '"buttocks"',
 '"fair"',
 '6-8',
 '99',
 '"improved"',
 'ABD pain',
 '0/.10',
 'withdraws from pain',
 'vented.',
 'yes - R arm',
 '8-9/10',
 '8 ',
 '"no pain"',
 'unwilling',
 '7-7.5',
 'awake',
 '"some pain"',
 '"mucho"',
 '2-10 ',
 'pt did not answer ',
 'asleep, ',
 'na',
 '"Yes"',
 'crit ',
 '03/10',
 'headache ',
 'groaning',
 'Ambulatory Triage',
 'patient sleeping',
 'not really',
 '7/laying',
 'uncomfortable',
 'yelling',
 '2-4',
 '5-9',
 '6.4',
 'says no but....',
 'more comf',
 'unable to use pain scale, appears restless',
 '"pain" in back tht "is alwys  there"',
 'appears less restless, unable to describe pain using pain scale.',
 '3-7',
 'unabke',
 'i',
 '--',
 'trigger',
 'no facial grimace',
 'no grimace',
 'yes/unable to #',
 'A little better',
 'asleep, denies pain when aroused',
 'back pain - unable to score',
 'int',
 'unable; intubated',
 '5.8',
 'anable',
 '"fine" "better"',
 ')',
 'o/10',
 'rectal',
 'oral',
 '0 asleep',
 '?7',
 'declined to answer',
 '"Not bad"',
 'less sharp',
 '2-8',
 'red',
 'appears comfortable. ',
 '" a little"',
 'unalble',
 'Assumed pain s/p CXR',
 'sleeping.',
 'mucho',
 'unable to state',
 'pain with palpation',
 '.3',
 '"tight"',
 '10:10',
 'SLeeping',
 'Yes',
 '3.',
 '9.9',
 'nad',
 'unbale',
 '8.7',
 ' 6',
 '5                               m ',
 'facial grimicing when touching pt',
 '0.3',
 'fine',
 'less',
 '7.5-8',
 '"pretty good" ',
 'somnolent',
 '0-1/10',
 '09',
 'high',
 '0/0',
 '`',
 'Im not having pain but i feel something s/p nitro x2',
 '6oral ',
 '...',
 'somulnet',
 'somulent',
 '0-7',
 'Patient sleeping',
 '2-10',
 'sleeping on/off',
 'ambulatory @ saturation',
 'sleepy',
 'sleepingg',
 '0/19',
 'ua ',
 'ETCO2 45',
 'ETCO2 59',
 'Seizing',
 'U/A',
 'layinh down, denies dizziness',
 'sitting denies dizziness',
 'standing, dneies dizziness',
 '"pain in neck"',
 'unable to answer',
 'rectal pain',
 '   8',
 '5/6',
 '2L',
 'CONFUSED',
 'Unable ',
 'crtitcal',
 'assumed',
 'standing denies ',
 '0unable ',
 'intubated.',
 'unable   ',
 'Sedated',
 'unable no nonverbal cues',
 'NC',
 'standing up',
 'laying down ',
 '"not much" ',
 '"unwell" ',
 '6 w mvt ',
 'not apparent',
 'unable to answer ',
 '`7',
 'pt unable to score',
 '"it\'s gone"',
 '+10',
 'una',
 'asleeep',
 'xc',
 'sleeping   ',
 '(unable)',
 '8/10 both head and neck',
 'awake ',
 'extreme',
 '0 c',
 '"same"',
 'NRB',
 '"throbbing"',
 'Room Air',
 '2/0',
 'unabe',
 'slepping',
 '5/0',
 'LAYING ',
 '?unable to assess',
 '"pains"',
 'C',
 '8,10',
 '6 or 7',
 'resting with eyes closed',
 '"little bit"',
 'snoring',
 '-0',
 'while sleeping',
 'FACES 4',
 '3/10HA',
 '5.',
 'un able',
 'AMS',
 'decline to answer',
 '2liters',
 '0 at present ',
 '11/10',
 'utaa',
 'nausea',
 'peal flow 220',
 'peak flow 250',
 'peak flow 260',
 'peak flow 210',
 'peak flow 240',
 '"un poquito"',
 'flat',
 'confused',
 'slleeping',
 'all over',
 'altered',
 '1-2/6w mvt',
 'critcal',
 'my head hurts',
 'my head',
 'NAD noted',
 'sleeping in naps',
 'unablke',
 '0 - laying',
 '0 - standing',
 '0a ',
 '0-+',
 '"palpitations"',
 'Left Arm',
 'asleep, easily arousable',
 "'better'",
 'unble',
 "uncomfortable '4'",
 'none',
 '"almost gone"',
 '"mucho dolor"',
 "'little bit'",
 'see note',
 '"11"',
 'tua',
 'sleeing',
 'unable to scale but c/o generalized body pain',
 'Laying Flat',
 '"yes, left side"',
 'feet',
 'pt unable to verbalize ',
 '1/ 10',
 'Refuses',
 'unrable',
 'Refuse',
 'Declined',
 '"only when moving" ',
 'etc02 43',
 'etc02 39',
 'prehosp ',
 'nonverbal',
 '8 HA',
 'non verbal-no facial grimicing',
 'pt sleeping',
 'left without VS',
 '03',
 '0.1',
 '7 when standing',
 'pt left prior',
 'sleeping. ',
 '"oye"',
 '10:10 ',
 '8:10',
 'unable.',
 'numb',
 'unable/asleep',
 '0. ',
 '"weak"',
 '"not bad" ',
 'vent ',
 'PF350',
 '"not too much"',
 '6s',
 'Facial Grimaces ',
 '"pain is a little worse, I don\'t need anything though"',
 '10 with movement',
 'sleepugb',
 'discomfort',
 '3-9/10',
 '1-2/10',
 'chronic',
 '8/6',
 'low',
 '0/sleeping',
 '5/9',
 'Severe',
 'pain+',
 '098.0',
 'little better',
 '0*/10',
 'unable to',
 'Manual BP',
 'nodded yes',
 'unable 10+',
 '"so bad"',
 'unable to express',
 '" my occiput"',
 '6ha',
 'yes ',
 'CP',
 'sleepiong',
 'sleepign',
 'siting',
 '7 ',
 'L arm',
 'eyes closed/resting',
 'crying ',
 '0       ',
 'other ',
 '9/10 N ',
 '3 -',
 'no pain',
 '4-7',
 'intubated ',
 '"6"',
 "high fowler's",
 "semi fowler's",
 'Intubated',
 'right',
 'o/1-0',
 '5-7',
 'sedation ',
 'unknow n',
 "sleeping'",
 '"a little bit"',
 '8/',
 'uta.',
 'orthostatic',
 'off sedation',
 '3/10-10/10',
 '"lower back from laying on stretcher".',
 'sleeping (on side)',
 'laying down- denies dizziness ',
 'sitting- denies dizziness',
 'standing- denies dizziness',
 'little bit',
 'unablw',
 'uncomf.',
 'PF 300',
 'c                                                                                                                                                                                                                                                                                                                                                                                                     c',
 'utd',
 ')/10',
 'does not appear in distress',
 '"100"',
 'calm',
 'comfortable ',
 '8;10',
 '"alittle"',
 'pre-transfusion ',
 'fifteen min',
 'lousy',
 'burning',
 'q/u',
 'with movement',
 'severe',
 '2 ',
 '0R',
 '"YES"',
 '2/3',
 '0173/70',
 'Manual',
 '6.5-7',
 '"ow"',
 '6/10 cp',
 '0 cp, hip pain still 4/10',
 'Orthos-Sitting',
 'Orthos-Standing',
 'refused toa nswer',
 'I dont know',
 'IN',
 'no signs of pain',
 'napping',
 'Lying',
 'resting ',
 '"12"',
 'CVP 12',
 'un',
 '0 at rest, 7 when coughing',
 '5 ',
 'pain ',
 '3w palp',
 ' " a little better"',
 '10/10 LUQ',
 '9/10 chest',
 '7/10 luq',
 'NAAD',
 'not able',
 'REFUSED',
 'down to 2',
 '"OK"',
 'slepeing',
 'mild CP',
 'after neb',
 '3/10 at rest, 6-8/10 w/ mvmt.',
 '4-5 with movement',
 'asleepd',
 'FACES 0',
 'unable to tell',
 'Critical ',
 'trach',
 'sleepjung',
 'unable to obtain',
 'Refused ',
 'peak flow 275 before neb',
 '"calm"',
 'UA ',
 'says none',
 '2 tolerable ',
 'Pt sleeping',
 'with amulation',
 'Unable to assess',
 '"ok when I don\'t  move"',
 'u./a',
 'ON SIDE',
 'unable/sleeping',
 '3/10 manual',
 '0/10ra',
 'lge cuff',
 '0u',
 '     7                                                                                     7               ',
 '0Pt ',
 'uA',
 '0/10 at rest',
 'sleepgin',
 'arousable to sternal rub',
 'arousable to voice',
 'sleepinfg ',
 'refused to answer ',
 'L hip',
 'l hip',
 'unable to scaore - c/o pain everywhere',
 'dull',
 'pt states no change',
 '5fs',
 'pretty bad',
 '(Asleep)',
 'UAT',
 'unable, restless',
 'unable, more comfortable',
 'unable, comfortable',
 'manual',
 '"achy"',
 '3 rectal pain',
 '"The same"',
 'ambulatory ',
 '" ok right now"',
 '13',
 'back pain, unable to rate on numerical pain scale',
 'Right arm',
 '\\3',
 '0 - at rest',
 '4/10 ',
 'ambulatory sat',
 'Sit',
 'Stand',
 '6 ',
 '2-5',
 ' c',
 'sleepig',
 'stading',
 'layind down',
 'Standing ',
 'unable to eval',
 '"heaviness"',
 '"JUST SORE"',
 ' 3',
 'unable to int',
 '"still up there"',
 'unable to assess ',
 '"not much"',
 'fs190',
 '+HA',
 'sleeping/snoring',
 '"everywhere"',
 'rsting',
 '7 abd pain',
 'uTA',
 '43',
 'Ref',
 '"fine"',
 "'discomfort'",
 'uanle',
 'l',
 ...]

## Explore medrecon

In [30]:
medrecon.head()

,subject_id,stay_id,charttime,name,gsn,ndc,etc_rn,etccode,etcdescription
0,10000032,32952584,2180-07-22 17:26:00,albuterol sulfate,28090,21695042308,1,5970.0,Asthma/COPD Therapy - Beta 2-Adrenergic Agents...
1,10000032,32952584,2180-07-22 17:26:00,calcium carbonate,1340,10135021101,1,733.0,Minerals and Electrolytes - Calcium Replacement
2,10000032,32952584,2180-07-22 17:26:00,cholecalciferol (vitamin D3),65241,37205024678,1,670.0,Vitamins - D Derivatives
3,10000032,32952584,2180-07-22 17:26:00,emtricitabine-tenofovir [Truvada],57883,35356007003,1,5849.0,Antiretroviral - Nucleoside and Nucleotide Ana...
4,10000032,32952584,2180-07-22 17:26:00,fluticasone [Flovent HFA],21251,49999061401,1,371.0,Asthma Therapy - Inhaled Corticosteroids (Gluc...

In [31]:
medrecon.etc_rn.unique().tolist()

[1, 2, 3, 4, 5]

In [32]:
medrecon.etcdescription.unique().tolist()

['Asthma/COPD Therapy - Beta 2-Adrenergic Agents, Inhaled, Short Acting',
 'Minerals and Electrolytes - Calcium Replacement',
 'Vitamins - D Derivatives',
 'Antiretroviral - Nucleoside and Nucleotide Analog RTIs Combinations',
 'Asthma Therapy - Inhaled Corticosteroids (Glucocorticoids)',
 'Diuretic - Loop',
 'Colonic Acidifier (Ammonia Inhibitor)',
 'Smoking Deterrents - Nicotine-Type',
 'Laxative - Saline/Osmotic Mixtures',
 'Antiretroviral - HIV-1 Integrase Strand Transfer Inhibitors',
 'Rifamycins and Related Derivative Antibiotics',
 'Antibacterial Folate Antagonist - Other Combinations',
 'Asthma/COPD - Anticholinergic Agents, Inhaled Long Acting',
 'Analgesic Opioid Agonists',
 'Asthma/COPD - Anticholinergic Agents, Inhaled Short Acting',
 'Diuretic - Aldosterone Receptor Antagonist, Non-selective',
 'Aldosterone Receptor Antagonists',
 'Analgesic or Antipyretic Non-Opioid',
 'Antihistamines - 2nd Generation',
 'Antihistamines - 2nd Generation - Piperidines',
 'Antiparkinson Therapy - Monoamine Oxidase Inhibitor(MAO-B)',
 'Antiparkinson Therapy - Non-ergot Dopamine Agonist Agents',
 'Antihyperlipidemic - HMG CoA Reductase Inhibitors (statins)',
 "Alzheimer's Disease Therapy - Cholinesterase Inhibitors",
 'Antipsychotic -Atypical Dopamine-Serotonin Antag-Dibenzothiazepine Der',
 'Bipolar Therapy Agents - Atypical Antipsychotics',
 'Penicillin Antibiotic - Natural',
 'Gastric Acid Secretion Reducing Agents - Proton Pump Inhibitors (PPIs)',
 nan,
 'NSAID Analgesics (COX Non-Specific) - Propionic Acid Derivatives',
 'Antiemetic - Antihistamines',
 'NSAID Analgesics (COX Non-Specific) - Oxicam Derivatives',
 'Insulin Response Enhancers - Biguanides',
 'Diuretic - Potassium Sparing-Thiazide and Related Combinations',
 'Beta Blockers Cardiac Selective',
 'Platelet Aggregation Inhibitors - Thienopyridine Agents',
 'Salicylate Analgesics',
 'Platelet Aggregation Inhibitors - Salicylates',
 'Alternative Therapy - Antiarthritics',
 'Dermatological - Topical Local Anesthetic Amides',
 'Bone Resorption Inhibitors - Bisphosphonates',
 'Smoking Deterrents - NE and Dopamine Reuptake Inhibitor (NDRI)-Type',
 'Anticonvulsant - GABA Analogs',
 'Antiemetic - Selective Serotonin 5-HT3 Antagonists',
 'Antipsychotic - Phenothiazines, Piperazine',
 'Antiemetic - Phenothiazines',
 'Antidepressant - Selective Serotonin Reuptake Inhibitors (SSRIs)',
 'Skeletal Muscle Relaxant - Central Muscle Relaxants',
 'Antidepressant - Serotonin-2 Antagonist-Reuptake Inhibitors (SARIs)',
 'Dermatological - Glucocorticoid',
 'Vitamins - B-12, Cyanocobalamin and derivatives',
 'Low Molecular Weight Heparins',
 'Laxative - Surfactant',
 'Dietary Product - Dietary Supplements',
 'Laxative - Saline and Osmotic',
 'Medical Supplies and DME - Blood Glucose Tests',
 'Medical Supply, FDB Superset',
 'Antihistamine - 1st Generation - Ethanolamines',
 'Antihistamines - 1st Generation',
 'Minerals and Electrolytes - Iron',
 'Human Insulins - Fixed Combinations',
 'ACE Inhibitors',
 'Multivitamins',
 'Calcium Channel Blockers - Dihydropyridines',
 'Antianginal - Coronary Vasodilators (Nitrates)',
 'Gastric Acid Secretion Reducers - Histamine H2-Receptor Antagonists',
 'Medical Supplies and DME - Glucose Monitoring Test Supplies',
 'Phosphate Binders',
 'Hyperuricemia Therapy - Xanthine Oxidase Inhibitors',
 'Hyperparathyroid Treatment Agents - Vitamin D Analog-Type',
 'Alpha-Beta Blockers',
 'Medical Supplies and DME - Insulin Needles-Syringes and Admin Supplies',
 'Anticoagulants - Coumarin',
 'Central Alpha-2 Receptor Agonists',
 'Diuretic - Thiazides and Related',
 'Laxative - Stimulant',
 'Asthma/COPD Therapy - Beta Adrenergic Agents',
 'Antianxiety Agent - Benzodiazepines',
 'Benzodiazepines',
 'Insulin Analogs - Rapid Acting',
 'Insulin Analogs - Long Acting',
 'Analgesic Opioid Hydrocodone Combinations',
 'Analgesic Opioid Hydrocodone and Non-Salicylate Combinations',
 'Cephalosporin Antibiotics - 3rd Generation',
 'Anticonvulsant - Pyrrolidine Derivatives',
 'Antiprotozoal-Antibacterial 1st Generation 2-methyl-5-nitroimidazole',
 'Analgesic Opioid Oxycodone Combinations',
 'Analgesic Opioid Oxycodone and Non-Salicylate Combinations',
 'Migraine Therapy - Selective Serotonin Agonists 5-HT(1)',
 'B-Complex Vitamins',
 'Antihyperlipidemic Agents - Dietary Source Combinations',
 'Nasal Corticosteroids',
 'Anticonvulsant - Benzodiazepines',
 'Vaginal Estrogens',
 'NSAID Analgesics (COX Non-Specific) - Other',
 'Fibromyalgia Agents - GABA Analogs',
 'Beta Blockers Non-Cardiac Selective',
 'Systemic Sympathomimetic Decongestants',
 'Thyroid Hormones - Synthetic T4 (Thyroxine)',
 'Angiotensin II Receptor Blockers (ARBs)',
 'Vitamins - C, Ascorbic Acid and Derivatives',
 'Fluoroquinolone Antibiotics',
 'Herpes Antiviral Agent - Purine Analogs',
 'Contraceptive Oral - Progestin',
 'Cardiovascular Sympathomimetic - Anaphylaxis Therapy Single Agents',
 'Contraceptive Oral - Monophasic',
 'Digitalis Glycosides',
 'Direct Factor Xa Inhibitors',
 'Asthma/COPD Therapy - Beta Adrenergic-Glucocorticoid Combinations',
 'Antihistamines - 2nd Generation - Piperazines',
 'CNS Stimulant - Amphetamine Combinations',
 'Attention Deficit-Hyperactivity (ADHD) Therapy, Stimulant-Type',
 'Anorectal - Hemorrhoidal Rectal Glucocorticoid-Local Anesthetic Comb',
 'Nasal Anticholinergics',
 'Dermatological - Antifungal-Glucocorticoid Combinations',
 'Minerals and Electrolytes - Potassium, Oral',
 'Estrogens',
 'Antihyperlipidemic - Fibric Acid Derivatives',
 'Inflammatory Bowel Agent - Aminosalicylates and Related Agents',
 'Geriatric Vitamins',
 'Antihyperglycemic - Sulfonylurea Derivatives',
 "Alzheimer's Disease Therapy - NMDA Receptor Antagonists",
 'Antiarrhythmic - Class III',
 'Minerals and Electrolytes - Calcium Replacement/Vitamin D Combinations',
 'Vaginal Antifungal - Imidazoles',
 'Opioid Antitussive-Expectorant Combinations',
 'Calcium Channel Blockers - Benzothiazepines',
 'Ophthalmic - Carbonic Anhydrase Inhibitors',
 'Ophthalmic-Intraocular Pressure Reducing Agents, Prostaglandin Analogs',
 'Glucocorticoids',
 'Asthma Therapy - Xanthines',
 'Analgesic Opioid Codeine Combinations',
 'Aminopenicillin Antibiotic',
 'Asthma Therapy - Leukotriene Receptor Antagonists',
 'Smoking Deterrents - Nicotinic Receptor Partial Agonist, alpha4beta2',
 'Multivitamin and Mineral Combinations',
 'Minerals and Electrolytes - Magnesium',
 'Alternative Therapy - Unclassified',
 'Antifungal - Triazoles',
 'Nutritional Product - Nutritional Therapy',
 'Acne Therapy Topical - Anti-infective',
 'Dermatological - Antifungal Amphoteric Polyene Macrolides',
 'Antitussives - Non-Opioid',
 'Dermatological - Rosacea Therapy, Topical',
 'Medical Supplies and DME - Respiratory Therapy Supplies',
 'Antiseptic - Biguanides',
 'Antihyperglycemic - Sodium Glucose Cotransporter-2 (SGLT2) Inhibitors',
 'Alternative Therapy - Antioxidant',
 'Selective Estrogen Receptor Modulators (SERMs)',
 'Antidepressant-Norepinephrine and Dopamine Reuptake Inhibitors (NDRIs)',
 'Antianxiety Agent - Non-Benzodiazepine',
 'Ophthalmic Antibiotic - Macrolides',
 'Mouth and Throat - Saliva Stimulants',
 'Diuretic - Carbonic Anhydrase Inhibitors',
 'Heparins',
 'Antidepressant - Alpha-2 Receptor Antagonists (NaSSA)',
 'Antipsychotic - Atypical Dopamine-Serotonin Antag- Benzisoxazole Deriv',
 'Glycopeptide Antibiotics',
 'Artificial Tears and Lubricant Combinations',
 'Narcolepsy Therapy Agents - Stimulant-Type, Piperadine Derivative',
 'Ophthalmic - Decongestant-Astringent Combinations',
 'Intestinal Flora Modifiers',
 'Prostatic Hypertrophy Agent - alpha-1-Adrenoceptor Antagonists',
 'Gout Acute Therapy - Antimitotics',
 'ACE Inhibitor and Diuretic Combinations',
 'DMARD - Antimetabolites',
 'Antineoplastic - Antimetabolite - Folic Acid Analogs',
 'Antidepressant-Tricyclics and Related (Non-Select Reuptake Inhibitors)',
 'Prenatal Vitamins and Minerals',
 'Sedative-Hypnotic - GABA-Receptor Modulators',
 'Analgesic or Antipyretic Non-Opioid/Sedative Combinations',
 'Gallstone Solubilizing (Litholysis) Agents',
 'Agents for Opioid Withdrawal, Opioid-Type',
 'Antihyperlipidemic Agents - Dietary Source',
 'Patent Ductus Arteriosus (PDA) Treatment Agents , NSAID-type',
 'Vitamins - Folic Acid and Derivatives',
 'Inflammatory Bowel Agent - Tumor Necrosis Factor Alpha Blockers',
 'Anti-inflammatory Tumor Necrosis Factor Inhibiting Agnts,TNF-alpha Sel',
 'DMARD - Antinflammatory, Select. costimulation modulator,T-cell Inhib.',
 'Antiparkinson - Dopaminerg-Peripheral Dopa-decarboxylase Inhibit Comb',
 'Antacid - Antacid Combinations',
 'Minerals and Electrolytes - Calcium Replacement Combinations',
 'Urinary Antispasmodic - Smooth Muscle Relaxants',
 'Sodium Chloride Flushes',
 'Wound Care - Dressings',
 'Antidepressant - Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)',
 'Antacid - Simethicone Combinations',
 'Dermatological - Local Anesthetic Combinations',
 'Dermatological - Antibacterial Other',
 'Ophthalmic - Intraocular Pressure Reducing Agents, Beta-blockers',
 'Dermatological - Antifungal Imidazole and Related Agents',
 'Ophthalmic Antibiotic - Fluoroquinolones',
 'Antiretroviral- Nucleoside and Nucleotide Analogs,Integrase Inhibitors',
 'Protease Inhibitors (Non-Peptidic) Antiretroviral',
 'Protease Inhibitors (Peptidic) Antiretroviral',
 'Aminopenicillin Antibiotic - Beta-lactamase Inhibitor Combinations',
 'Dermatological - Antifungal Hydroxypyridinone',
 'Granulocyte Colony-Stimulating Factor (G-CSF)',
 'Immunosuppressive - Purine Analogs',
 'DMARD - Immunosuppressives',
 'Methotrexate Rescue Agents - Folic Acid Antagonist Type',
 'Methotrexate Rescue Agents',
 'Laxative - Stimulant and Surfactant Combinations',
 'Calcimimetic, Parathyroid Calcium Receptor Sensitivity Enhancer',
 'Mouth and Throat - Local Anesthetic Amides',
 'Antineoplastic - Thalidomide Analogs',
 'Laxative - Bulk Forming',
 'Macrolide Antibiotics',
 'Urinary Analgesics',
 'Antacid - Calcium',
 'Thrombin Inhibitor - Selective Direct and Reversible',
 'Dermatological - NSAID Single Agents',
 'Bulk Chemicals',
 'Pharmaceutical Adjuvant - Cream/Ointment Vehicles',
 "Dermatological - Antineoplastic or Premalignant Lesions - NSAID's",
 'Nasal Moisturizers',
 'Anticonvulsant - Phenyltriazine Derivatives',
 'Antipsychotic - Atypical Dopamine-Serotonin Antag-Dibenzodiazepine Der',
 'Salicylate Analgesic Combinations',
 'Anorectal - Glucocorticoids',
 'Vaginal Antifungal - Triazoles',
 'Androgen - Single Agents',
 'Amino Acids, Single Ingredient, Oral (non-injectable)',
 'Vitamins - B-3, Niacin and Derivatives',
 'Minerals and Electrolytes - Trace Minerals',
 'Vitamins - E',
 'Urinary Antibacterial - Nitrofuran Derivatives',
 'Antibacterial Nitrofuran Derivatives',
 'Otic (Ear) - Fluoroquinolones',
 'Gastrointestinal Antiflatulents',
 'Dermatological - Antibacterial-Glucocorticoid Combinations',
 'Otic (Ear) - Wax Removers-Softeners',
 'Anticonvulsant - Carboxylic Acid Derivatives',
 'Bipolar Therapy Agents -  Anticonvulsant Type',
 'Musculoskeletal Tx Agent-Joint Contracture Therapy, Collagenase Enzyme',
 'Vaccine Viral - Varicella',
 'Live Vaccine and Live Virus Formulations',
 'Antipsychotic -Atypical Dopamine-Serotonin Antag-Thienobenzodiazepines',
 'Migraine Therapy - Carboxylic Acid Derivatives',
 'Non-Opioid Antitussive-Expectorant Combinations',
 'Fibromyalgia Agents - Serotonin-Norepinephrine Reuptake-Inhib (SNRIs)',
 'Contraceptive Intrauterine - Progesterone IUD',
 'Erectile Dysfunction (ED) Drugs-Sel.cGMP Phosphodiesterase Type5 Inhib',
 'Digestive Enzymes',
 'Antidiarrheal - Antiperistaltic Agents',
 'Antiretroviral-Nucleoside, Nucleotide Analogs and Non-Nucleoside RTI',
 'Contraceptive Implant - Progestin',
 'Calcium Channel Blockers - Phenylakylamines',
 'Acne Therapy Topical - Anti-infective-Keratolytic Combinations',
 'Lincosamide Antibiotics',
 'Vitamins - B Preparation Combinations',
 'Vitamins - Folic Acid Combinations',
 'Antihyperglycemic - Dipeptidyl Peptidase-4 (DPP-4) Inhibitors',
 'Antihyperlipidemic - Selective Cholesterol Absorption Inhibitor',
 'Anorexiants',
 'Bioflavonoid Combinations',
 'Antipsychotic-Atypical,D2 Receptor Partial Agonist-5HT Serotonin Mixed',
 'Immunosuppressive - Calcineurin Inhibitors',
 'Immunosuppressive - Inosine Monophosphate Dehydrogenase Inhibitors',
 'Narcolepsy Therapy Agents - Non-Sympathomimetic',
 'Ophthalmic - Anti-inflammatory, Immunomodulators',
 'Tetracycline Antibiotics',
 'DMARD - Other',
 'Anticonvulsant - Monosaccharide Derivatives',
 'Urinary Antispasmodic - Antichol., M(3) Muscarinic Selective (Bladder)',
 'Vitamins - B-1, Thiamine and Derivatives',
 'Anorectal - Hemorrhoidal Single Agents Other',
 'Contraceptives - Intravaginal, Systemic - Estrogen and Progestin Comb.',
 'Peptic Ulcer - Treatment of H. Pylori: Antibiotic-Bismuth Combinations',
 'Mouth and Throat - Antifungals',
 'Antihyperglycemic, Incretin Mimetic,GLP-1 Receptor Agonist Analog-Type',
 'Antacid - Bicarbonate',
 'Human Insulins - Intermediate Acting',
 'Peptic Ulcer - Gastric Lumen Adherent Cytoprotectives',
 'Acne Therapy Systemic - Tetracyclines',
 'Vitamins - B-12 and Folic Acid Combinations',
 'Insulin Response Enhancers - Thiazolidinediones (PPAR-gamma agonists)',
 'Asthma/COPD Therapy - Beta Adrenergic-Anticholinergic Combinations',
 'Contraceptive Oral - Triphasic',
 'Oxazolidinone Antibiotics',
 'Digestive Enzyme Mixtures',
 'Antineoplastic - Selective Estrogen Receptor Modulators (SERMs)',
 'Human Insulins - Short Acting',
 'Antifungal - Glucan Synthesis Inhibitors (Echinocandins)',
 'Alcohol Abstinence Therapy - Glutamate and GABA System Type',
 'Antidiarrheal Antiperistaltic-Anticholinergic Combinations',
 'Acne Therapy Topical - Retinoids and Derivatives',
 'Dermatological Irritants-Counter-Irritant Single Agents',
 'Antianxiety Agent - Antihistamine Type',
 'Gastrointestinal Prokinetic Agents - D2 Antagonist/5-HT4 Agonists',
 'Ophthalmic - Antihistamine-Decongestant Combinations',
 'Pseudobulbar Affect (PBA) Agents, NMDA antagonists type',
 'Metabolic Modifier - Carnitine Replenisher Agents',
 'Minerals and Electrolytes - Iron Combinations',
 'Direct Acting Vasodilators',
 'Antineoplastic - Aromatase Inhibitors',
 'Hypnotics - Melatonin - Single Agents',
 'Angiotensin II Receptor Blocker (ARB)-Diuretic Combinations',
 'Emergency Contraceptives',
 'Emergency Contraceptives - Progestin Type',
 'Contraceptive Oral - Biphasic',
 'Antipsychotic - Butyrophenone Derivatives',
 'Opioid Reversal Agents - Opioid Antagonists',
 'Vitamins - Biotin',
 'Antiretroviral-Nucleoside Reverse Transcriptase Inhibitors (NRTI) Comb',
 'Prostatic Hypertrophy Agent - Type II 5-alpha Reductase Inhibitors',
 'Dermatological - Antibacterial Erythromycins',
 'Ophthalmic Antibacterial Mixtures',
 'GI Antispasmodic - Synthetic Tertiary Amines',
 'Antimalarials',
 'DMARD - Antimalarials',
 'NSAID Analgesic, Cyclooxygenase-2 (COX-2) Selective Inhibitors',
 'Irritable Bowel Syndrome (IBS) Agents',
 'IBS Agent - Guanylate Cyclase-C (GC-C) Agonists',
 'Analgesic - Neuronal (N)-Type Calcium Channel Blockers (NCCBs)',
 'Interstitial Cystitis Agents',
 'Platelet Aggregation Inhibitor Combinations',
 'Minerals and Electrolytes - Zinc',
 'Influenza Antiviral Agents - Neuraminidase Inhibitors',
 'Peripheral Alpha-1 Receptor Blockers',
 'Antiretroviral-Nucleoside Analogs and Integrase Inhibitor combinations',
 'Antiretroviral - Nucleoside Reverse Transcriptase Inhibitors (NRTI)',
 'Alternative Therapy - Pineal Hormone Agents',
 'Cardiovascular Sympathomimetics',
 'Ophthalmic - Decongestants',
 'Dental Product - Fluoride Preparations',
 'Antiarrhythmic - Class Ic',
 'Antidepressant - MAO Inhibitor Nonselective and Irreversible-Types A,B',
 'B-Complex Vitamin Combinations',
 'Thyroid Hormones - Animal Source (Porcine)',
 'Narcolepsy Therapy Agents- Stimulant-Type,Sympathomimetic,Amphetamines',
 'Analgesic Opioid Hydrocodone and NSAID Combinations',
 'Ophthalmic-Intraocular Press. Reducing, Sel. Alpha Adrenergic Agonists',
 'Ophthalmic - Beta blockers-Carbonic Anhydrase Inhibitor Combinations',
 'Sedative-Hypnotic - Antihistamines',
 'Antiparkinson Therapy - Anticholinergic Agents',
 'LHRH (GnRH) Agonist Analog Pituitary Suppressants',
 'Hepatitis C - Nucleoside Analogs',
 'Sedative-Hypnotic - Benzodiazepines',
 'Sedative-Hypnotic - Barbiturates',
 'Anticonvulsant - Barbiturates and Derivatives',
 'Antineoplastic - Antimetabolite - Urea Derivatives',
 'Anticonvulsant - Hydantoins',
 'Cardiac Selective Beta Blocker-Thiazide Diuretic and Related Comb.',
 'Asthma/COPD Therapy - Beta 2-Adrenergic Agents, Inhaled, Long Acting',
 'Somatostatic Agents',
 'Short Bowel Syndrome (SBS) Agents',
 'Antiprotozoal Agents - Other',
 'Antithyroid Agents, Thionamides - Imidazole Derivatives',
 'Antihyperlipidemic - Bile Acid Sequestrants',
 'Factor VIII Preparations (AHF)',
 'Antiretroviral - CCR5 Co-Receptor Antagonist',
 'Analgesic,Non-Salicylate and 1st Generation Antihistamine Combinations',
 'Dermatological - Antipruritics Combinations',
 'Platelet Aggregation Inhibitors - Phosphodiesterase III Inhibitors',
 'Bipolar Therapy Agents - Lithium',
 'Antipsychotic - Atypical Dopamine-Serotonin Antag- Benzisothiazolones',
 'Antiseptic - Alcohols',
 'Insulin Analogs - Fixed Combinations',
 'Agents to treat Hypoglycemia (Hyperglycemics)',
 'Antineoplastic - B-cell lymphoma-2 (BCL-2) inhibitors',
 'Mouth and Throat - Lozenges',
 'Antineoplastic - Protein-Tyrosine Kinase Inhibitors',
 "Antineoplastic - Bruton's tyrosine kinase (BTK) inhibitor",
 'Dermatological - Calcineurin Inhibitors',
 'Analgesic Opioid Partial-Mixed Agonists',
 'Inflammatory Bowel Agent - Glucocorticoids',
 'Cephalosporin Antibiotics - 1st Generation',
 'Peptic Ulcer-Treatment H. Pylori-Proton Pump Inhibitor and Antibiotics',
 'Attention Deficit-Hyperact. Disorder (ADHD)- alpha-2 Receptor Agonist',
 'Attention Deficit-Hyperactivity Disorder (ADHD) Therapy, NRI-Type',
 'Ophthalmic - Antihistamines',
 'Fertility Enhancer - Ovulation Stimulant - Synthetic (Non-FSH)',
 'Nasal Antihistamines',
 'Phosphate Binders - Calcium-based',
 'Erythropoietins',
 'Pulmonary Arterial Hypertension Agents-Selective cGMP-PDE5 Inhibitors',
 'Antiarrhythmic - Class IV',
 'Cephalosporin Antibiotics - 4th Generation',
 'Expectorants - Single Agents, General',
 'Antihistamine - 1st Generation - Alkylamines',
 'Antihistamine - 1st Generation - Phenothiazines',
 'Platelet Aggregation Inhib - Cyclopentyl-triazolo-pyrimidines (CPTPs)',
 'Ophthalmic - Anti-inflammatory, Glucocorticoids',
 'Antineoplastic - Antiandrogens',
 'Antineoplastic - LHRH (GnRH) Agonist Analog Pituitary Suppressants',
 'GI Antispasmodic - Belladonna Alkaloids',
 'Urinary Alkalinizer - Citrates',
 'Contraceptive Injectable - Progestin',
 'Minerals and Electrolytes - Parenteral Electrolyte Combinations',
 'Vitamins - A',
 'Nasal Sympathomimetic Decongestants (Intranasal)',
 'Minerals and Electrolytes - Bicarbonate Producing or Containing Agents',
 'Minerals and Electrolytes - Phosphate',
 'Medical Supplies and DME - Incontinence Supplies',
 'Antipsychotic - Phenothiazines, Aliphatic',
 'Diuretic - Inorganic Salt',
 'Urinary Acidifier - Others',
 'Antiemetic - Anticholinergics',
 'Prostatic Hypertrophy Agent-Sel.cGMP Phosphodiesterase Type5 Inhibitor',
 'Immunosuppressive - Mammalian Target of Rapamycin (mTOR) Inhibitors',
 'Analgesic Opioid Tramadol Combinations',
 'Analgesic Opioid Tramadol and Non-Salicylate Combinations',
 'DMARD - Anti-inflammatory Tumor Necrosis Factor Inhibiting Agents',
 'Anti-inflammatory Tumor Necrosis Factor Inhibiting Agnts,Non-SeIective',
 'Anticonvulsant - Iminostilbene Derivatives',
 'NSAID Analgesics (COX Non-Specific) - Phenylacetic Acid Derivatives',
 '2nd Generation Antihistamine-Decongestant Combinations',
 'NSAID Analgesics, (COX Non-specific) - Indole Acetic Acid Derivatives',
 'Asthma Therapy - Mast Cell Stabilizers',
 'Antitubercular - Isonicotinic Acid Derivatives',
 'Vitamins - B-6, Pyridoxine and Derivatives',

In [33]:
medrecon.name.unique().tolist()

['albuterol sulfate',
 'calcium carbonate',
 'cholecalciferol (vitamin D3)',
 'emtricitabine-tenofovir [Truvada]',
 'fluticasone [Flovent HFA]',
 'furosemide',
 'lactulose',
 'nicotine',
 'peg 3350-electrolytes',
 'raltegravir [Isentress]',
 'rifaximin [Xifaxan]',
 'sulfamethoxazole-trimethoprim',
 'tiotropium bromide [Spiriva with HandiHaler]',
 'tramadol',
 'ergocalciferol (vitamin D2)',
 'ipratropium bromide [Atrovent HFA]',
 'spironolactone [Aldactone]',
 'spironolactone',
 'Tylenol Extra Strength',
 'loratadine',
 'Azilect',
 'pramipexole',
 'Pravachol',
 'rivastigmine',
 'Seroquel',
 'pravastatin',
 'rasagiline',
 'penicillin V potassium',
 'omeprazole magnesium [Prilosec]',
 '*HTN med ',
 'Ibuprofen IB',
 'ibuprofen',
 'meclizine [Antivert]',
 'meloxicam',
 'metformin',
 'triamterene-hydrochlorothiazid',
 'omeprazole',
 'metoprolol tartrate',
 'Plavix',
 'aspirin',
 'glucosamine-chondroitin',
 'atorvastatin [Lipitor]',
 'lidocaine',
 'omeprazole [Prilosec]',
 'Reclast',
 'Vitamin D-3',
 'Albuterol Sulfate',
 'bupropion HCl [Budeprion SR]',
 'gabapentin',
 'ondansetron HCl',
 'prochlorperazine maleate',
 'sertraline',
 'simvastatin',
 'tizanidine',
 'trazodone',
 'Triamcinolone Acetonide',
 'Vitamin B-12',
 'enoxaparin',
 'oxycodone',
 'Budeprion SR',
 'docusate sodium',
 'food supplement, lactose-free [Ensure]',
 'polyethylene glycol 3350',
 'Celexa',
 'blood sugar diagnostic',
 'clopidogrel [Plavix]',
 'diphenhydramine HCl [Sleep Aid (diphenhydramine)]',
 'ferrous sulfate [Feosol]',
 'insulin NPH & regular human [Humulin 70/30]',
 'lisinopril',
 'multivitamin',
 'nifedipine',
 'nitroglycerin [Nitrostat]',
 'ranitidine HCl',
 'ReliOn Ultra Thin Plus Lancets',
 'sevelamer carbonate [Renvela]',
 'allopurinol',
 'atorvastatin',
 'calcitriol',
 'carvedilol',
 'insulin NPH and regular human [Humulin 70/30]',
 'torsemide',
 'acetaminophen',
 'blood sugar diagnostic [OneTouch Ultra Test]',
 'furosemide [Lasix]',
 'lancets [OneTouch UltraSoft Lancets]',
 'pantoprazole',
 'pen needle, diabetic [BD Insulin Pen Needle UF Short]',
 'warfarin',
 'atenolol',
 'clonidine',
 'Enteric Coated Aspirin',
 'Humulin 70/30',
 'hydrochlorothiazide',
 'Nifediac CC',
 'Nitrostat',
 'sennosides [Senna-Gen]',
 'Vitamin D3',
 'polyethylene glycol 3350 [Miralax]',
 'Flovent HFA',
 'bisacodyl',
 'Phillips Milk of Magnesia',
 'senna',
 'amlodipine',
 'Aspirin',
 'Ativan',
 'Furosemide',
 'Humalog',
 'Lantus',
 'Lexapro',
 'Lisinopril',
 'Metformin',
 'Simvastatin',
 'Stool Softener',
 'Vicodin',
 'Mapap (acetaminophen)',
 'ceftriaxone',
 'levetiracetam',
 'metronidazole',
 'Percocet',
 'Axert',
 'B50 Balanced',
 'Calcium Citrate',
 'Cholecalciferol (Vitamin D3)',
 'Fish Oil',
 'Fluticasone',
 'lorazepam',
 'Multivitamin',
 'Omeprazole',
 'Zantac',
 'almotriptan malate [Axert]',
 'clonazepam',
 'estradiol',
 'fluticasone',
 'nabumetone',
 'pregabalin [Lyrica]',
 'propranolol',
 'pseudoephedrine HCl [Sudafed 12 Hour]',
 'alprazolam [Xanax]',
 'levothyroxine',
 'losartan',
 'ascorbic acid (vitamin C) [Acerola C]',
 'ciprofloxacin HCl [Cipro]',
 'enoxaparin [Lovenox]',
 'ferrous sulfate [Iron (ferrous sulfate)]',
 'valacyclovir',
 'Camila',
 'EpiPen 2-Pak',
 'Sprintec (28)',
 'levofloxacin',
 'digoxin',
 'Eliquis',
 'albuterol sulfate [ProAir HFA]',
 'budesonide-formoterol [Symbicort]',
 'cetirizine',
 'dextroamphetamine-amphetamine [Adderall XR]',
 'epinephrine',
 'hydrocortisone-pramoxine',
 'ipratropium bromide',
 'lorazepam [Ativan]',
 'metolazone',
 'nystatin-triamcinolone',
 'potassium chloride [Klor-Con M20]',
 'clobetasol',
 'epinephrine [Auvi-Q]',
 'Coumadin',
 'Tricor',
 'Asacol HD',
 'Vitamin D2',
 'Centrum Silver',
 'glipiZIDE',
 'isosorbide dinitrate',
 'metoprolol succinate',
 'Namenda',
 'Namenda Titration Pak',
 'amiodarone',
 'calcium citrate-vitamin D3 [Calcium Citrate +]',
 'clotrimazole [Gyne-Lotrimin]',
 'codeine-guaifenesin',
 'cod liver oil',
 'diltiazem HCl',
 'dorzolamide',
 'fluticasone-salmeterol [Advair Diskus]',
 'isosorbide mononitrate',
 'latanoprost',
 'prednisone',
 'theophylline',
 'docusate sodium [Colace]',
 'ferrous sulfate',
 'acetaminophen-codeine',
 'amoxicillin',
 'Calcium Citrate +',
 'ketorolac',
 'ProAir HFA',
 'Spiriva with HandiHaler',
 'Symbicort',
 'zafirlukast',
 'Zocor',
 'clopidogrel',
 'varenicline [Chantix Starting Month Pak]',
 'Xarelto',
 'cefpodoxime',
 'Colace',
 'apixaban',
 'multivitamin with minerals',
 'tiotropium bromide',
 'simvastatin [Zocor]',
 'dexamethasone',
 'magnesium',
 'potassium',
 'ubiquinol-B12-FA-resveratrol',
 'Reclipsen (28)',
 'fluconazole [Diflucan]',
 'Glucerna Shake',
 'Humalog KwikPen',
 'insulin glargine [Lantus Solostar]',
 'Lantus Solostar',
 'MetroLotion',
 'NovoFine 30',
 'nystatin',
 'oxycodone-acetaminophen',
 'ropinirole',
 'acetaminophen [Acetaminophen Extra Strength]',
 'benzonatate',
 'blood-glucose meter',
 'blood sugar diagnostic [FreeStyle Lite Strips]',
 'fluticasone propionate [Flovent HFA]',
 'insulin aspart U-100 [Novolog Flexpen U-100 Insulin]',
 'insulin needles (disposable) [BD Insulin Pen Needle UF Mini]',
 'metronidazole [MetroLotion]',
 'montelukast',
 'nebulizer and compressor',
 'nitroglycerin',
 'pen needle, diabetic [BD Ultra-Fine Nano Pen Needles]',
 'sennosides [senna]',
 'insulin aspart [Novolog Flexpen]',
 'insulin detemir [Levemir FlexTouch]',
 'carisoprodol',
 'insulin detemir [Levemir Flexpen]',
 'methocarbamol',
 'Levemir',
 'Ecotrin',
 'Lipitor',
 'potassium chloride',
 'insulin lispro [Humalog KwikPen]',
 'insulin needles (disposable) [NovoFine 30]',
 'Levemir Flexpen',
 'salsalate',
 'chlorhexidine gluconate',
 'Jardiance',
 'Toujeo SoloStar U-300 Insulin',
 'Ascorbic Acid',
 'aspirin [Lo-Dose Aspirin]',
 'Calcium with Vitamin D',
 'donepezil [Aricept]',
 'Glucosamine',
 'Ocuvite',
 'raloxifene [Evista]',
 'bupropion HCl',
 'buspirone',
 'norgestimate-ethinyl estradiol [Mononessa (28)]',
 'lidocaine [Lidoderm]',
 'erythromycin',
 'lovastatin',
 'Multiple Vitamin, Womens',
 'hydromorphone',
 'nebulizer and compressor [Portable Nebulizer System]',
 'cetirizine [Zyrtec]',
 'clotrimazole',
 'fluticasone [Flonase Allergy Relief]',
 'warfarin [Jantoven]',
 'alendronate',
 'aspirin [Aspir-81]',
 'Calcium',
 'desonide',
 'Levoxyl',
 'triamcinolone acetonide',
 'Tylenol',
 'pilocarpine HCl',
 'acetazolamide',
 'heparin (porcine)',
 'mirtazapine',
 'risperidone',
 'vancomycin',
 'Artificial Tears',
 'methylphenidate',
 'Biotene Oralbalance',
 'Natural Calcium',
 'tetrahydrozoline-zinc',
 '*nutrient drink ',
 'bifidobacterium infantis [Align]',
 'cefdinir',
 'Coenzyme Q10',
 'Crestor',
 'Dyazide',
 'losartan [Cozaar]',
 'tamsulosin [Flomax]',
 'Bifidobacterium infantis [Align]',
 'famotidine',
 'colchicine',
 'lisinopril-hydrochlorothiazide',
 'methotrexate',
 '*birth control',
 'nortriptyline',
 'prenatal vit-iron fumarate-FA [Prenatal Vitamin with Minerals]',
 'Ambien',
 'Amlodipine',
 'Diovan',
 'estradiol [Estrace]',
 'Fioricet',
 'Lorazepam',
 'Metoprolol Succinate',
 'Tramadol',
 'ursodiol',
 'High Potency Calcium',
 '*no-spa',
 'conjugated estrogens [Premarin]',
 'tamsulosin',
 'Suboxone',
 '*MALIC ACID',
 'B-12 Plus',
 'glucosam-chondroit-C-manganese',
 'Flagyl',
 'Levaquin',
 'Benadryl',
 'Indocin',
 '*',
 'Prilosec',
 'Omega-3',
 'coenzyme Q10',
 'folic acid',
 'methotrexate sodium',
 'Remicade',
 'abatacept (with maltose) [Orencia (with maltose)]',
 'carbidopa-levodopa',
 'aluminum hydrox-magnesium carb [Gaviscon]',
 'calcium-vitamin D3-vitamin K [Viactiv]',
 'epinephrine [EpiPen]',
 'oxybutynin chloride',
 'sodium chloride 0.9 % [Normal Saline Flush]',
 'silver-hydrocolloid dressing [Aquacel-AG]',
 'venlafaxine',
 'gabapentin [Neurontin]',
 'alum-mag hydroxide-simeth [Liquid Antacid]',
 'lidocaine-prilocaine',
 'mupirocin',
 'Betimol',
 'Calcium Citrate-Vitamin D3',
 'Ketoconazole',
 'ciprofloxacin HCl',
 'timolol [Betimol]',
 'omeprazole magnesium [Prilosec OTC]',
 'peg-electrolyte soln [NuLYTELY with Flavor Packs]',
 'peg-electrolyte soln [PEG-3350 with flavor packs]',
 'Prenatal Multivitamins',
 'amitriptyline',
 'Genvoya',
 'Prezista',
 'ferrous gluconate',
 'Truvada',
 'Norvir',
 'Humalog U-100 Insulin',
 'insulin glargine',
 'HumaLOG',
 'Augmentin',
 'acyclovir',
 'ciclopirox [Loprox]',
 'fexofenadine [Allegra]',
 'fluconazole',
 'fluoxetine',
 'amoxicillin-pot clavulanate',
 'filgrastim [Neupogen]',
 'azathioprine',
 'hydrocodone-acetaminophen',
 'Aleve',
 'Tylenol Ex Str Rapid Release',
 'norethindrone-e.estradiol-iron',
 'Inderal LA',
 'Nexium',
 'leucovorin calcium',
 'PERI-COLACE',
 'Bayer Aspirin',
 'aspirin [Adult Low Dose Aspirin]',
 'cinacalcet [Sensipar]',
 'omega-3 fatty acids',
 'ondansetron',
 'lidocaine HCl [Lidocaine Viscous]',
 'Folic Acid',
 'nicotine (polacrilex)',
 'rosuvastatin [Crestor]',
 'Klor-Con 10',
 'Warfarin',
 'diltiazem HCl [DILT-XR]',
 'lenalidomide [Revlimid]',
 'psyllium husk [Metamucil]',
 'sennosides [Senna Lax]',
 'clarithromycin',
 'docusate calcium',
 'phenazopyridine',
 'Lasix',
 'Revlimid',
 'calcium carbonate [Tums]',
 'cyanocobalamin (vitamin B-12)',
 'dabigatran etexilate [Pradaxa]',
 'multivitamin with iron-mineral',
 'pantoprazole [Protonix]',
 'diclofenac sodium [Voltaren]',
 'meclizine',
 'diclofenac sodium [Solaraze]',
 'naproxen',
 'Saline Nasal',
 'iron',
 'warfarin [Coumadin]',
 'Cozaar',
 'Lamictal',
 'amphetamine-dextroamphetamine [Adderall XR]',
 'Risperidone',
 'Klonopin',
 'clozapine',
 'gemfibrozil',
 'insulin glargine [Lantus]',
 'Excedrin Migraine',
 'butalbital-acetaminophen-caff',
 'diazepam',
 'hydrocortisone acetate',
 'terconazole',
 'AndroGel',
 'glutamine',
 'magnesium citrate',
 'Niacin Flush Free',
 'phosphatidylcholine (bulk)',
 'Pulmicort Flexhaler',
 'selenium',
 'vitamin E',
 'glycine',
 'lysine',
 'Junel FE 1/20 (28)',
 'Macrobid',
 'famotidine [Acid Controller]',
 'labetalol',
 'levetiracetam [Keppra]',
 'Keppra',
 'ofloxacin',
 'simethicone [Gas Relief]',
 'neomy-polymyxinB-bacitracin-HC [Cortisporin]',
 'simethicone [Gas Relief 80]',
 'alprazolam',
 'Aspir-81',
 'Claritin',
 'Lovastatin',
 'Protonix',
 'Singulair',
 'carbamide peroxide',
 'Depakote',
 'fluocinonide',
 'hydrocortisone',
 'ketoconazole',
 'Xiaflex',
 'zoster vaccine live (PF) [Zostavax (PF)]',
 'Zyprexa',
 'citalopram',
 'Depakote ER',
 'Laxative (bisacodyl)',
 'Fleet Enema',
 'Robafen DM Cough-Chest Congest',
 '*birth control pill',
 'Wellbutrin',
 'Wellbutrin SR',
 'escitalopram oxalate',
 'duloxetine [Cymbalta]',
 'levonorgestrel [Mirena]',
 'sildenafil [Viagra]',
 'Acetaminophen',
 'Buspirone',
 'Cyanocobalamin',
 'Lactaid Fast Act',
 'Loperamide',
 'Tussin DM',
 'Ortho-Cyclen (28)',
 'multivitamin-iron-folic acid [Centrum Complete]',
 'Cipro',
 'cyclobenzaprine',
 'emtricita-rilpivirine-tenof DF',
 'Nexplanon',
 'Complera',
 'Allergy Relief (fluticasone)',
 'Lyrica',
 'Dilaudid',
 'Pepcid AC',
 'chlorthalidone',
 'verapamil',
 'Odefsey',
 'sulfacetamide-sulfur-cleansr23',
 'methylphenidate HCl',
 'sildenafil',
 'Concerta',
 'clindamycin HCl',
 'Ecotrin Low Strength',
 'Folgard RX',
 'JanUVIA',
 'metFORMIN',
 'ZANtac',
 'ZeTIA',
 'Adipex-P',
 '*gout medication',
 'Calci-Chew',
 'Ester-C',
 'Abilify',
 'Cymbalta',
 'Neurontin',
 'lamotrigine',
 'calcium carbonate-vitamin D3 [Calcium 600 with Vitamin D3]',
 'cyclosporine modified [Neoral]',
 'ezetimibe [Zetia]',
 'glipizide',
 'mycophenolate mofetil',
 'quetiapine',
 'Citracal + D',
 'levothyroxine [Levoxyl]',
 'L-Lysine',
 'Provigil',
 'Probiotic',
 'Mirapex',
 'acetaminophen [Tylenol]',
 'calcium carbonate [Calcium 500]',
 'cyclosporine [Restasis]',
 'minocycline',
 'topiramate',
 'trospium',
 'modafinil',
 'solifenacin [Vesicare]',
 'calcium carbonate-vitamin D3 [Calcium 600 + D(3)]',
 'multivitamin [Daily Multiple]',
 'simethicone',
 'Lidoderm',
 'bisacodyl [Dulcolax (bisacodyl)]',
 'thiamine HCl (vitamin B1)',
 'fentanyl',
 'magnesium hydroxide [Milk of Magnesia]',
 'multivitamin,tx-minerals',
 'Apri',
 'ascorbic acid (vitamin C) [Vitamin C]',
 'fenofibrate',
 'levothyroxine [Levo-T]',
 'loperamide [Anti-Diarrhea]',
 'multivitamin-minerals-lutein [Multivitamin 50 Plus]',
 'polyvinyl alcohol-povidon(PF) [Refresh Classic (PF)]',
 'witch hazel [Tucks]',
 'etonogestrel-ethinyl estradiol [NuvaRing]',
 'bismuth subcit K-metronidz-tcn [Pylera]',
 'metoprolol succinate [Toprol XL]',
 'valsartan [Diovan]',
 'olanzapine',
 'docusate sodium [Stool Softener]',
 'pegfilgrastim [Neulasta]',
 'vitamin B complex [B Complex 1]',
 'diclofenac sodium',
 'rosuvastatin',
 'folic acid-vit B6-vit B12 [FaBB]',
 'betamethasone dipropionate',
 'Januvia',
 '*cholesterol med',
 'amlodipine [Norvasc]',
 'liraglutide [Victoza 2-Pak]',
 'sodium bicarbonate',
 'sitagliptin [Januvia]',
 'aspirin [Enteric Coated Aspirin]',
 'cyanocobalamin (vitamin B-12) [Vitamin B-12]',
 'fluticasone [Flonase]',
 'multivitamin [Daily Multi-Vitamin]',
 'multivitamin,tx-iron-minerals [Thera-M]',
 'NPH insulin human recomb [Novolin N]',
 'sucralfate [Carafate]',
 'Prozac',
 'Paxil',
 'duloxetine',
 'phentermine',
 'darifenacin',
 'captopril',
 'cranberry',
 'lactobacillus acidophilus [Acidophilus]',
 'mesalamine [Canasa]',
 'mesalamine [Lialda]',
 'omega-3 fatty acids-vitamin E [Fish Oil]',
 'turmeric (bulk) [Curcumin]',
 'vitamin B12-folic acid',
 'glyburide',
 'pioglitazone',
 'fluticasone-salmeterol',
 'ipratropium-albuterol',
 'norgestimate-ethinyl estradiol [Tri-Sprintec (28)]',
 'linezolid [Zyvox]',
 'lipase-protease-amylase [Pancrelipase 5000]',
 'tamoxifen',
 'hydromorphone [Dilaudid]',
 'insulin regular human',
 'micafungin [Mycamine]',
 'saccharomyces boulardii [Florastor]',
 'acamprosate [Campral]',
 'diphenoxylate-atropine',
 'efavirenz-emtricitabin-tenofov [ATRIPLA]',
 'tretinoin',
 'efavirenz-emtricitabin-tenofov',
 'Valium',
 'capsaicin',
 'hydroxyzine pamoate',
 'metoclopramide HCl',
 'acamprosate',
 'hydroxyzine pamoate [Vistaril]',
 'olanzapine [Zyprexa]',
 'Atripla',
 'ATRIPLA',
 'Clobetasol',
 'metoclopramide',
 'Calcium Carbonate',
 'Multivitamins with Minerals',
 'naphazoline-pheniramine [Opcon-A]',
 'Fosamax',
 'fluvoxamine',
 'Nuedexta',
 'Carnitor',
 'Docusil',
 'Avapro',
 'PreserVision',
 'Spectravite',
 'Novolog Flexpen',
 'hydralazine',
 'PreserVision AREDS',
 'Novolog PenFill',
 'Miralax',
 'Multiple Vitamins',
 'exemestane',
 'melatonin',
 'sumatriptan succinate [Imitrex]',
 'losartan-hydrochlorothiazide',
 'Norvasc',
 'Requip',
 'Calcium 600 + D(3)',
 'amLODIPine',
 'calcium',
 'Combivent',
 'Motrin',
 'levonorgestrel',
 'L norgest&E estradiol-E estrad [Amethia]',
 'Zoloft',
 'Topamax',
 'haloperidol',
 'hydroxyzine HCl',
 'Effexor XR',
 'naltrexone',
 'Vistaril',
 'Remeron',
 '*ACAMPROSATE CALC DR  ',
 'Vitamin B-1',
 'insulin NPH and regular human',
 'biotin',
 'Calcium Carbonate-Vit D3-Min',
 'chondroitin sulfate A',
 'prenat.vits,cal,min-iron-folic',
 'abacavir-lamivudine [Epzicom]',
 'atazanavir [Reyataz]',
 'ritonavir [Norvir]',
 'sulfamethoxazole-trimethoprim [Bactrim]',
 'valacyclovir [Valtrex]',
 '*blood pressure medication ',
 'finasteride',
 'clindamycin phosphate',
 'Wellbutrin XL',
 'Luvox CR',
 'polymyxin B sulf-trimethoprim',
 'dicyclomine',
 'lamotrigine [Lamictal]',
 'Plaquenil',
 'Allegra Allergy',
 'M-Vit',
 'Novolog',
 'ZyrTEC',
 'colchicine [Colcrys]',
 'food supplemt, lactose-reduced [Ensure Plus]',
 'azithromycin',
 'norgestimate-ethinyl estradiol [Sprintec (28)]',
 'erythromycin with ethanol',
 'celecoxib [Celebrex]',
 'ergocalciferol (vitamin D2) [Vitamin D2]',
 'esomeprazole magnesium [Nexium]',
 'linaclotide',
 'ondansetron [Zofran ODT]',
 'ranitidine HCl [Zantac]',
 'methadone',
 'Prialt',
 'Celebrex',
 'sumatriptan succinate',
 'baclofen',
 'Elmiron',
 'morphine',
 'bisoprolol fumarate',
 'ramipril',
 'Aggrenox',
 'Colcrys',
 'ascorbic acid',
 'ferrous sulfate [iron]',
 'quetiapine [Seroquel]',
 'zinc sulfate',
 'dipyridamole-aspirin [Aggrenox]',
 'One Daily Multivitamin',
 'insulin lispro',
 'prochlorperazine [Compazine]',
 'Acidophilus',
 'calcium carbonate [Calci-Chew]',
 'esomeprazole magnesium',
 'irbesartan',
 'calcium carb &cit-vit D3',
 'calcium carbonate-vitamin D3 [Calcarb 600 With Vitamin D]',
 'Tamiflu',
 'bupropion HCl (smoking deter)',
 'cetirizine [All Day Allergy (cetirizine)]',
 'doxazosin',
 'testosterone enanthate',
 'zolpidem [Ambien]',
 'Triumeq',
 'darunavir',
 'Isentress',
 'Cardura',
 'Emtriva',
 'emtricitabine [Emtriva]',
 'tadalafil [Cialis]',
 'morphine [MS Contin]',
 'magnesium oxide',
 'midodrine',
 'multivitamin-iron-folic acid',
 'naphazoline-hypromellose',
 'sodium fluoride',
 'tolterodine',
 '*calcium 600mg/ d400 tablet',
 'flaxseed',
 'Nuvigil',
 'hydroxychloroquine [Plaquenil]',
 'moexipril',
 'clotrimazole-betamethasone [Lotrisone]',
 'tolterodine [Detrol]',
 'Toprol XL',
 'Reglan',
 'Natural Senna Laxative',
 'Therapeutic Vitamin & Mineral',
 'Ritalin',
 'Ovcon-35 (28)',
 'flecainide',
 'selegiline HCl',
 'Emsam',
 'ascorbic acid [Vitamin C]',
 'nitrofurantoin macrocrystal',
 'Bisacodyl',
 "Women's Laxative (bisacodyl)",
 'Calcarb 600 With Vitamin D',
 'B complex with C 20-folic acid',
 'rifaximin',
 'sevelamer carbonate',
 'Antioxidant Formula',
 'B-50 Complex',
 'calcium citrate',
 'fiber',
 'garlic',
 'grape seed extract',
 'omega-3 fatty acids [Fish Oil Concentrate]',
 'saw palmetto',
 'thyroid (pork) [Westhroid]',
 'Westhroid',
 'doxycycline hyclate',
 'Adderall XR',
 'Adderall',
 'Valtrex',
 'ciprofloxacin',
 'Synthroid',
 'Loratadine',
 'Actonel',
 'Ibuprofen',
 'hydrocodone-ibuprofen',
 'Bactrim',
 'brimonidine',
 'dorzolamide-timolol',
 'doxepin',
 'Estrace',
 'Zostavax (PF)',
 'diphenhydramine HCl',
 'acetaminophen [Tylenol Extra Strength]',
 'Cogentin',
 'Imuran',
 'zolpidem',
 'anastrozole',
 'aripiprazole [Abilify]',
 'dextroamphetamine-amphetamine [Adderall]',
 'Lupron Depot (3 Month)',
 'ribavirin',
 'Advil',
 'albuterol sulfate [Ventolin HFA]',
 'calcium citrate-vitamin D3',
 'celecoxib',
 'Calcium Carbonate-Vitamin D3',
 'EC Aspirin',
 'Lactaid',
 'Lysine',
 'Magnesium',
 'Vitamin C',
 'calcium carbonate-vitamin D3',
 "Centrum Ultra Women's",
 'levothyroxine [Synthroid]',
 'phenobarbital',
 'hydroxyurea',
 'Dilantin Kapseal',
 'Advair Diskus',
 'phenytoin sodium extended [Dilantin Extended]',
 'atenolol-chlorthalidone',
 'primidone',
 'Calcium-Cholecalciferol (D3)',
 'Isosource 1.5 Cal',
 'salmeterol [Serevent Diskus]',
 'Sandostatin LAR Depot',
 'Serevent Diskus',
 'oxycodone-acetaminophen [Roxicet]',
 'lycopene',
 'milk thistle',
 'valsartan',
 'Zyrtec',
 'Ultram',
 'atovaquone',
 'GlycoLax',
 'cholecalciferol (vitamin D3) [Vitamin D3]',
 '*revelimid',
 'methimazole',
 'calcium carbonate-vit D3-min',
 'calcium carbonate-vitamin D3 [Calcium 500 + D]',
 'colesevelam',
 'Levemir U-100 Insulin',
 'fosinopril',
 'Meloxicam',
 'Unithroid',
 'Itch Relief (clotrimazole)',
 'Voltaren',
 'Cosopt',
 'liraglutide',
 'Alphagan P',
 'Zanaflex',
 'Victoza 2-Pak',
 'ADVATE',
 'nadolol',
 'zidovudine',
 'maraviroc [Selzentry]',
 'insulin lispro [Humalog]',
 'diltiazem HCl [DILT-CD]',
 'Bactrim DS',
 'oxycodone-acetaminophen [Percocet]',
 'Carvedilol',
 'Imdur',
 'mycophenolate mofetil [CellCept]',
 'tacrolimus [Prograf]',
 'timolol',
 'Tylenol PM Extra Strength',
 'Vision Formula(A-C-E-Zn-Se-Cu)',
 'donepezil',
 'Proctosol HC',
 'Benefiber Sugar Free(Guar Gum)',
 'ProctoCream-HC',
 'Roxicet',
 'calcium carbonate-vitamin D3 [Os-Cal 500 + D3]',
 'camphor-menthol [Sarna Anti-Itch]',
 'cilostazol',
 'naproxen sodium',
 'Spectravite Senior',
 'Zometa',
 'Junel 1/20 (21)',
 'calcium-magnesium',
 'lactobacillus rhamnosus GG [Probiotic]',
 'lithium carbonate',
 'flaxseed oil',
 'Vitamin D',
 'Co Q-10',
 'venlafaxine [Effexor XR]',
 'acetaminophen [Mapap (acetaminophen)]',
 'divalproex [Depakote]',
 'ziprasidone HCl',
 'alcohol swabs',
 'blood-glucose meter [Blood Glucose Monitoring]',
 'blood-glucose meter [FreeStyle Freedom Lite]',
 'blood sugar diagnostic [OneTouch Verio]',
 'camphor-menthol [Anti-Itch (menthol/camphor)]',
 'carbamide peroxide [Ear Wax Removal Kit]',