In [1]:
import polars as pl
df = pl.read_csv("/home/fares-ashraf/snap/dbeaver-ce/471/risk_predictions_202604292347.csv")

In [2]:
df.head()

shape: (5, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ risk_pred ┆ stay_id  ┆ subject_i ┆ model_nam ┆ … ┆ risk_labe ┆ threshold ┆ top_featu ┆ created_a │
│ iction_id ┆ ---      ┆ d         ┆ e         ┆   ┆ l         ┆ _used     ┆ res       ┆ t         │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆          ┆ i64       ┆ str       ┆   ┆ str       ┆ f64       ┆ str       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1         ┆ 30000012 ┆ 11714491  ┆ asclena_x ┆ … ┆ HIGH      ┆ 0.4       ┆ [{"featur ┆ 2026-04-2 │
│           ┆          ┆           ┆ gboost_ri ┆   ┆           ┆           ┆ e": "vita ┆ 9 21:52:0 │
│           ┆          ┆           ┆ sk        ┆   ┆           ┆           ┆ l_row_cou ┆ 8.521     │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ nt"…      ┆           │
│ 2         ┆ 30000017 ┆ 14230614  ┆ asclena_x ┆ … ┆ LOW       ┆ 0.4       ┆ [{"featur ┆ 2026-04-2 │
│           ┆          ┆           ┆ gboost_ri ┆   ┆           ┆           ┆ e": "vita ┆ 9 21:52:0 │
│           ┆          ┆           ┆ sk        ┆   ┆           ┆           ┆ l_row_cou ┆ 8.521     │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ nt"…      ┆           │
│ 3         ┆ 30000038 ┆ 13821532  ┆ asclena_x ┆ … ┆ HIGH      ┆ 0.4       ┆ [{"featur ┆ 2026-04-2 │
│           ┆          ┆           ┆ gboost_ri ┆   ┆           ┆           ┆ e": "vita ┆ 9 21:52:0 │
│           ┆          ┆           ┆ sk        ┆   ┆           ┆           ┆ l_row_cou ┆ 8.521     │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ nt"…      ┆           │
│ 4         ┆ 30000039 ┆ 13340997  ┆ asclena_x ┆ … ┆ HIGH      ┆ 0.4       ┆ [{"featur ┆ 2026-04-2 │
│           ┆          ┆           ┆ gboost_ri ┆   ┆           ┆           ┆ e": "vita ┆ 9 21:52:0 │
│           ┆          ┆           ┆ sk        ┆   ┆           ┆           ┆ l_row_cou ┆ 8.521     │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ nt"…      ┆           │
│ 5         ┆ 30000055 ┆ 19848164  ┆ asclena_x ┆ … ┆ LOW       ┆ 0.4       ┆ [{"featur ┆ 2026-04-2 │
│           ┆          ┆           ┆ gboost_ri ┆   ┆           ┆           ┆ e": "vita ┆ 9 21:52:0 │
│           ┆          ┆           ┆ sk        ┆   ┆           ┆           ┆ l_row_cou ┆ 8.521     │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ nt"…      ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
df.select(pl.col("risk_label").value_counts())

shape: (3, 1)
┌────────────────────┐
│ risk_label         │
│ ---                │
│ struct[2]          │
╞════════════════════╡
│ {"HIGH",142242}    │
│ {"MODERATE",97352} │
│ {"LOW",185493}     │
└────────────────────┘